name: ci

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: codeberg-medium-lazy
        steps:
            - name: "test"
              shell: bash
              run: echo "$MESSAGE";
              env:
                MESSAGE: ${{ inputs.message }}
