name: ci

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:
        
jobs:
    test:
        runs-on: codeberg-medium-lazy
        steps:
            - name: "test"
              run: bash echo "foo";