name: Test Lua Actions.
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: windows-2019
    strategy:
      matrix:
        luaVersion: ["luajit-2.1.0-beta3"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Lua
        uses: xpol/setup-lua@v0.2
        with:
          lua-version: ${{ matrix.luaVersion }}
      - name: Setup Luarocks
        uses: leafo/gh-actions-luarocks@v2
      - name: Install package(s)
        run: |
          luarocks install winapi


