name: Test Lua Actions.
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: windows-2019
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "luajit-2.1.0-beta3"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}
