name: Winpy.

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python#v3
        with:
          python-version: '3.x'
      - run: python win.py
