name: Test Python Actions.
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python .\\.github\\workflows\\win.py
