name: Test Lua Actions.
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    runs-on: windows-2019
    strategy:
      matrix:
        luaVersion: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Lua
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.luaVersion }}
      - name: test
        run: |
          python .\\.github\\workflows\\win.py
